version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: magicwoods_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: SuperPuperPass!
      MYSQL_DATABASE: magic_woods_db
      MYSQL_USER: magician
      MYSQL_PASSWORD: AbraCadabra!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - magicwoods_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: magicwoods_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: SuperPuperPass!
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - magicwoods_network

volumes:
  mysql_data:

networks:
  magicwoods_network:
    driver: bridge 